services:
  app:
    build: .
    ports:
      
"8080:8080"
  environment:
MYSQL_HOST=localhost
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_DB=fiap
depends_on:
mysql

  mysql:
    image: mysql:5.7
    ports:
      
"3306:3306"
  environment:
  MYSQL_ROOT_PASSWORD=root
  MYSQL_DATABASE=fiap
volumes:
mysql-data:/var/lib/mysql

volumes:
  mysql-data: